required = ["github.com/prometheus/promu"]

# This is a fork of github.com/prometheus/node_exporter/collector.
ignored = ["github.com/prometheus/node_exporter*"]

[[constraint]]
  name = "github.com/mdlayher/wifi"
  revision = "567082929344b0af8eb8a2ad6fe4725c0b3c8702"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  revision = "aace68cde27da90f76be50fcb9937d67fd6a1968"

[[constraint]]
  name = "github.com/prometheus/promu"
  version = "=v0.1.0"

[[override]]
  name = "github.com/mdlayher/netlink"
  revision = "1291b75abe0cc0cb335f110466bf1f02590c916d"

[[override]]
  name = "github.com/prometheus/common"
  # Version before introducing kingpin.
  # https://github.com/prometheus/common/pull/96
  revision = "185c63bfc5a8c7a703687edb52940c895c818cb5"

[[override]]
  name = "github.com/spf13/viper"
  version = "=v1.0.3"

[[override]]
  name = "github.com/coreos/go-systemd"
  version = "=v21"

[[override]]
  name = "github.com/prometheus/procfs"
  revision = "7d6f385de8bea29190f15ba9931442a0eaef9af7"

[[override]]
  name = "github.com/percona/exporter_shared"
  revision = "7d9e9cc0256a3fbb559aa2f3fb9d8d37e3bd1bf5"
